// Copyright 2018 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package aws

// regionScope is the region binding of an AWS service generator.
//
//	scopeRegional  imported once per requested region
//	scopeGlobal    bound to a default region (IAM, Route53, CloudFront…);
//	               imported in the "aws-global" pass
//	scopeEastOnly  only works in us-east-1 (e.g. WAFv2 for CloudFront)
type regionScope int

const (
	scopeRegional regionScope = iota
	scopeGlobal
	scopeEastOnly
)

// serviceScope is the single declarative source of truth for every registered
// AWS service's region binding. scope_test.go asserts it against the registry
// (GetSupportedService) and against SupportedGlobalResources /
// SupportedEastOnlyResources — so adding a service to the registry without a
// scope, or misclassifying one, fails the build instead of silently importing
// into the wrong region path / failing to sign (the bug class fixed in
// commit c127700b). Every key needs an explicit entry, including regional, so
// the assertion can prove completeness.
var serviceScope = map[string]regionScope{
	// global — bound to a default region, imported in the aws-global pass
	"budgets":           scopeGlobal,
	"cloudfront":        scopeGlobal,
	"ecrpublic":         scopeGlobal,
	"globalaccelerator": scopeGlobal,
	"iam":               scopeGlobal,
	"organization":      scopeGlobal,
	"networkmanager":    scopeGlobal,
	"route53":           scopeGlobal,
	"shield":            scopeGlobal,
	"waf":               scopeGlobal,

	// us-east-1 only
	"cur":              scopeEastOnly,
	"route53domains":   scopeEastOnly,
	"wafv2_cloudfront": scopeEastOnly,

	// regional (default)
	"ce":                           scopeRegional,
	"chime-sdk-mediapipelines":     scopeRegional,
	"comprehend":                   scopeRegional,
	"rekognition":                  scopeRegional,
	"route53recoveryreadiness":     scopeRegional,
	"ssmquicksetup":                scopeRegional,
	"transcribe":                   scopeRegional,
	"appintegrations":              scopeRegional,
	"bcmdataexports":               scopeRegional,
	"chatbot":                      scopeRegional,
	"pinpointsmsvoicev2":           scopeRegional,
	"route53recoverycontrolconfig": scopeRegional,
	"verifiedaccess":               scopeRegional,
	"amp":                          scopeRegional,
	"appfabric":                    scopeRegional,
	"applicationinsights":          scopeRegional,
	"auditmanager":                 scopeRegional,
	"bedrock":                      scopeRegional,
	"bedrockagent":                 scopeRegional,
	"cleanrooms":                   scopeRegional,
	"cloudsearch":                  scopeRegional,
	"elastictranscoder":            scopeRegional,
	"evidently":                    scopeRegional,
	"ivschat":                      scopeRegional,
	"resiliencehub":                scopeRegional,
	"accessanalyzer":               scopeRegional,
	"acm":                          scopeRegional,
	"acm-pca":                      scopeRegional,
	"alb":                          scopeRegional,
	"amplify":                      scopeRegional,
	"appflow":                      scopeRegional,
	"appstream":                    scopeRegional,
	"connect":                      scopeRegional,
	"customer-profiles":            scopeRegional,
	"dataexchange":                 scopeRegional,
	"datazone":                     scopeRegional,
	"codeguru-reviewer":            scopeRegional,
	"codeguru-profiler":            scopeRegional,
	"codestar-notifications":       scopeRegional,
	"controltower":                 scopeRegional,
	"chime-sdk-voice":              scopeRegional,
	"autoscaling-plans":            scopeRegional,
	"docdb-elastic":                scopeRegional,
	"groundstation":                scopeRegional,
	"timestream-influxdb":          scopeRegional,
	"finspace":                     scopeRegional,
	"gamelift":                     scopeRegional,
	"greengrassv2":                 scopeRegional,
	"iotevents":                    scopeRegional,
	"iotsitewise":                  scopeRegional,
	"iottwinmaker":                 scopeRegional,
	"location":                     scopeRegional,
	"payment-cryptography":         scopeRegional,
	"pca-connector-ad":             scopeRegional,
	"servicecatalog-appregistry":   scopeRegional,
	"imagebuilder":                 scopeRegional,
	"ivs":                          scopeRegional,
	"lexv2-models":                 scopeRegional,
	"license-manager":              scopeRegional,
	"lightsail":                    scopeRegional,
	"m2":                           scopeRegional,
	"mediapackagev2":               scopeRegional,
	"pcs":                          scopeRegional,
	"route53profiles":              scopeRegional,
	"s3tables":                     scopeRegional,
	"ssm-contacts":                 scopeRegional,
	"ssm-incidents":                scopeRegional,
	"codeartifact":                 scopeRegional,
	"codestar-connections":         scopeRegional,
	"fis":                          scopeRegional,
	"grafana":                      scopeRegional,
	"healthlake":                   scopeRegional,
	"kendra":                       scopeRegional,
	"neptune-graph":                scopeRegional,
	"osis":                         scopeRegional,
	"pinpoint":                     scopeRegional,
	"proton":                       scopeRegional,
	"qbusiness":                    scopeRegional,
	"rbin":                         scopeRegional,
	"resource-explorer-2":          scopeRegional,
	"verifiedpermissions":          scopeRegional,
	"vpc-lattice":                  scopeRegional,
	"wellarchitected":              scopeRegional,
	"mediaconvert":                 scopeRegional,
	"quicksight":                   scopeRegional,
	"s3control":                    scopeRegional,
	"s3outposts":                   scopeRegional,
	"workspaces-web":               scopeRegional,
	"api_gateway":                  scopeRegional,
	"api_gatewayv2":                scopeRegional,
	"application-autoscaling":      scopeRegional,
	"appconfig":                    scopeRegional,
	"appmesh":                      scopeRegional,
	"apprunner":                    scopeRegional,
	"appsync":                      scopeRegional,
	"athena":                       scopeRegional,
	"auto_scaling":                 scopeRegional,
	"backup":                       scopeRegional,
	"batch":                        scopeRegional,
	"cloud9":                       scopeRegional,
	"cloudformation":               scopeRegional,
	"cloudhsm":                     scopeRegional,
	"cloudtrail":                   scopeRegional,
	"cloudwatch":                   scopeRegional,
	"codebuild":                    scopeRegional,
	"codecommit":                   scopeRegional,
	"codedeploy":                   scopeRegional,
	"codepipeline":                 scopeRegional,
	"cognito":                      scopeRegional,
	"config":                       scopeRegional,
	"customer_gateway":             scopeRegional,
	"datapipeline":                 scopeRegional,
	"datasync":                     scopeRegional,
	"dax":                          scopeRegional,
	"detective":                    scopeRegional,
	"devicefarm":                   scopeRegional,
	"dlm":                          scopeRegional,
	"dms":                          scopeRegional,
	"docdb":                        scopeRegional,
	"ds":                           scopeRegional,
	"dx":                           scopeRegional,
	"dynamodb":                     scopeRegional,
	"ebs":                          scopeRegional,
	"ec2_instance":                 scopeRegional,
	"ecr":                          scopeRegional,
	"ecs":                          scopeRegional,
	"efs":                          scopeRegional,
	"eip":                          scopeRegional,
	"eks":                          scopeRegional,
	"elastic_beanstalk":            scopeRegional,
	"elasticache":                  scopeRegional,
	"elb":                          scopeRegional,
	"emr":                          scopeRegional,
	"emr-containers":               scopeRegional,
	"emr-serverless":               scopeRegional,
	"eni":                          scopeRegional,
	"es":                           scopeRegional,
	"firehose":                     scopeRegional,
	"fms":                          scopeRegional,
	"fsx":                          scopeRegional,
	"glacier":                      scopeRegional,
	"glue":                         scopeRegional,
	"guardduty":                    scopeRegional,
	"identitystore":                scopeRegional,
	"inspector2":                   scopeRegional,
	"igw":                          scopeRegional,
	"iot":                          scopeRegional,
	"kafkaconnect":                 scopeRegional,
	"keyspaces":                    scopeRegional,
	"kinesis":                      scopeRegional,
	"kinesisanalyticsv2":           scopeRegional,
	"kinesisvideo":                 scopeRegional,
	"kms":                          scopeRegional,
	"lakeformation":                scopeRegional,
	"lambda":                       scopeRegional,
	"logs":                         scopeRegional,
	"macie2":                       scopeRegional,
	"media_package":                scopeRegional,
	"media_store":                  scopeRegional,
	"medialive":                    scopeRegional,
	"mq":                           scopeRegional,
	"memorydb":                     scopeRegional,
	"msk":                          scopeRegional,
	"mwaa":                         scopeRegional,
	"neptune":                      scopeRegional,
	"opensearch":                   scopeRegional,
	"opensearchserverless":         scopeRegional,
	"pipes":                        scopeRegional,
	"nacl":                         scopeRegional,
	"network-firewall":             scopeRegional,
	"rolesanywhere":                scopeRegional,
	"securitylake":                 scopeRegional,
	"nat":                          scopeRegional,
	"networkmonitor":               scopeRegional,
	"internetmonitor":              scopeRegional,
	"oam":                          scopeRegional,
	"rum":                          scopeRegional,
	"synthetics":                   scopeRegional,
	"opsworks":                     scopeRegional,
	"qldb":                         scopeRegional,
	"ram":                          scopeRegional,
	"rds":                          scopeRegional,
	"redshift":                     scopeRegional,
	"redshift-serverless":          scopeRegional,
	"sagemaker":                    scopeRegional,
	"scheduler":                    scopeRegional,
	"schemas":                      scopeRegional,
	"resourcegroups":               scopeRegional,
	"route53resolver":              scopeRegional,
	"route_table":                  scopeRegional,
	"s3":                           scopeRegional,
	"secretsmanager":               scopeRegional,
	"securityhub":                  scopeRegional,
	"servicecatalog":               scopeRegional,
	"servicediscovery":             scopeRegional,
	"servicequotas":                scopeRegional,
	"ses":                          scopeRegional,
	"sesv2":                        scopeRegional,
	"sfn":                          scopeRegional,
	"sg":                           scopeRegional,
	"sns":                          scopeRegional,
	"signer":                       scopeRegional,
	"sqs":                          scopeRegional,
	"sso-admin":                    scopeRegional,
	"ssm":                          scopeRegional,
	"storagegateway":               scopeRegional,
	"subnet":                       scopeRegional,
	"swf":                          scopeRegional,
	"timestream-write":             scopeRegional,
	"transfer":                     scopeRegional,
	"transit_gateway":              scopeRegional,
	"vpc":                          scopeRegional,
	"vpc_endpoint":                 scopeRegional,
	"vpc_peering":                  scopeRegional,
	"vpn_connection":               scopeRegional,
	"vpn_gateway":                  scopeRegional,
	"waf_regional":                 scopeRegional,
	"wafv2_regional":               scopeRegional,
	"workspaces":                   scopeRegional,
	"xray":                         scopeRegional,
}
