name: "tagged-release"
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        required: true
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Test
        run: make build test
      - name: Cross-compile release binaries (linux/mac, amd64+arm64)
        run: make release
      - name: Build for all providers
        run: make build-providers

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.event.inputs.version }}
          prerelease: false
          files: |
            terraformer-*
